runMachAr : main.c ../NRs/ansi/recipes/machar.c ../NRs/ansi/recipes/machar_for_double.c ../NRs/ansi/other/nr.h
	cc -o runMachAr main.c ../NRs/ansi/recipes/machar.c ../NRs/ansi/recipes/machar_for_double.c -I ../NRs/ansi/other
